### PR TITLE
Make record/union deserializers ignore unknown fields

### LINKED ISSUE #232: __nirum_deserialize__ of Union raise KeyError if extra items given.
```python
def test_union_extra_tag():
    n = CultureAgnosticName(fullname=u'foobar')
    serialized = n.__nirum_serialize__()
    serialized.update(wrong='v')
    with raises(ValueError):
        MixedName.__nirum_deserialize__(serialized)
```
While deserialize union with extra items, it raises unexpected `KeyError`. See above example.

### PR DESCRIPTION
**Pull request by dahlia**
Fixes #232.  See also *docs/refactoring.md* and *CHANGES.md*.

### CODE REVIEW

File: src/Nirum/Targets/Python.hs [hunk 1]
```diff
@@ -953,7 +953,7 @@ class $className(object):
             )
         args = dict()
         behind_names = cls.__nirum_field_names__.behind_names
-        field_types = cls.__nirum_field_types__
+        field_types = cls.__nirum_field_types__()
```
Comment (admire93) [inline src/Nirum/Targets/Python.hs]: 👀
